{% set name = "ppmac" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-HXN/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f3b1c89a4344c7063524f4d8e04b4c46bbebd02692236351190549a434dfe32b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.8
    - paramiko

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - ppmac

about:
  home: https://github.com/NSLS-II-HXN/ppmac
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Some Power PMAC Linux/Python tools

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
